CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  CREATE TYPE usuario_status AS ENUM ('ativo', 'inativo');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE usuario_cargo AS ENUM ('capataz', 'supervisor', 'gerente');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE tarefa_prioridade AS ENUM ('alta', 'media', 'baixa');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE tarefa_status AS ENUM ('pendente', 'em_andamento', 'concluida', 'cancelada');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ticket_categoria AS ENUM (
    'cerca',
    'hidraulica',
    'eletrica',
    'edificacao',
    'abastecimento_agua',
    'outro'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ticket_status AS ENUM ('aberto', 'em_atendimento', 'resolvido', 'cancelado');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ticket_prioridade AS ENUM ('alta', 'media', 'baixa');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE movimentacao_tipo AS ENUM (
    'nascimento',
    'morte',
    'transferencia',
    'compra',
    'venda',
    'outros'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE movimentacao_status AS ENUM ('pendente', 'aprovado', 'rejeitado');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE movimentacao_estagio_vida AS ENUM (
    'BEZERRO 0 A 7 MESES',
    'GARROTE 8 A 12 MESES',
    'NOVILHA 8 A 12 MESES',
    'GARROTE 13 A 24 MESES',
    'NOVILHA 13 A 24 MESES',
    'BOI 25 A 36 MESES',
    'NOVILHA 25 A 36 MESES',
    'TOURO 25 A 36 MESES',
    'VACA ACIMA 36 MESES',
    'BOI ACIMA 36 MESES',
    'TOURO ACIMA 36 MESES'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE evidencia_tipo AS ENUM ('foto', 'audio', 'mensagem');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE relatorio_tipo AS ENUM ('movimentacao', 'tarefas', 'tickets', 'consolidado');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS retiro (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL
);
