CREATE TABLE IF NOT EXISTS ticket (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retiro_id BIGINT NOT NULL,
  aberto_por UUID NOT NULL,
  categoria ticket_categoria NOT NULL,
  localizacao VARCHAR(255) NOT NULL,
  status ticket_status NOT NULL,
  atribuido_a UUID NULL,
  descricao VARCHAR(255) NOT NULL,
  prioridade ticket_prioridade NOT NULL,
  sincronizado BOOLEAN NOT NULL DEFAULT false,
  data_criacao DATE NOT NULL DEFAULT CURRENT_DATE,
  data_realizado DATE NOT NULL DEFAULT CURRENT_DATE
);

ALTER TABLE ticket
  ADD CONSTRAINT ticket_retiro_id_foreign
  FOREIGN KEY (retiro_id) REFERENCES retiro(id);

ALTER TABLE ticket
  ADD CONSTRAINT ticket_aberto_por_foreign
  FOREIGN KEY (aberto_por) REFERENCES usuario(id);

ALTER TABLE ticket
  ADD CONSTRAINT ticket_atribuido_a_foreign
  FOREIGN KEY (atribuido_a) REFERENCES usuario(id);
