CREATE TABLE IF NOT EXISTS evidencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID NOT NULL,
  tipo evidencia_tipo NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE evidencia
  ADD CONSTRAINT evidencia_usuario_id_foreign
  FOREIGN KEY (usuario_id) REFERENCES usuario(id);
