CREATE TABLE IF NOT EXISTS relatorio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gerado_por UUID NOT NULL,
  retiro_id BIGINT NOT NULL,
  tipo relatorio_tipo NOT NULL,
  data_inicio DATE NOT NULL,
  data_fim DATE NOT NULL,
  data_gerado TIMESTAMP NOT NULL DEFAULT NOW(),
  url_arquivo TEXT NOT NULL,
  FOREIGN KEY (gerado_por) REFERENCES usuario(id),
  FOREIGN KEY (retiro_id) REFERENCES retiro(id)
);
